/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package communication

import (
	"context"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"time"

	amf_context "github.com/free5gc/amf/internal/context"
	"github.com/free5gc/amf/internal/logger"
	"github.com/free5gc/amf/internal/sbi/producer"
	"github.com/free5gc/openapi"
	"github.com/free5gc/openapi/models"
	"github.com/gin-gonic/gin"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

// NonUeN2MessageTransfer - Namf_Communication Non UE N2 Message Transfer service Operation
func HTTPNonUeN2MessageTransfer(c *gin.Context) {
	logger.CommLog.Warnf("Handle Non Ue N2 Message Transfer is not implemented.")
	body, _ := ioutil.ReadAll(c.Request.Body)
	taiwanTimezone, err := time.LoadLocation("Asia/Taipei")
	if err != nil {
		fmt.Println("Error loading Taiwan timezone:", err)
		return
	}
	currentTime := time.Now().In(taiwanTimezone)
	logger.CommLog.Infof("Receive Non Ue N2 Message Transfer at %s", currentTime.Format("2006-01-02 15:04:05"))
	var message models.NonUeN2MessageTransferRequest
	message.JsonData = new(models.N2InformationTransferReqData)
	contentType := c.GetHeader("Content-Type")
	openapi.Deserialize(&message, body, contentType)
	insertToDatabase(message)
	amfSelf := amf_context.AMF_Self()
	producer.NonUeN2MessageTransferProcedure(amfSelf, message)
	c.JSON(http.StatusOK, gin.H{})
}

func insertToDatabase(message models.NonUeN2MessageTransferRequest) {
	clientOptions := options.Client().ApplyURI("mongodb://localhost:27017")
	client, err := mongo.Connect(context.TODO(), clientOptions)
	if err != nil {
		log.Fatal(err)
	}
	err = client.Ping(context.TODO(), nil)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("Connected to MongoDB!")
	collection := client.Database("local").Collection("AMFNonUeN2MessageTransfer")
	insertResult, err := collection.InsertOne(context.TODO(), message)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Inserted document ID: %v\n", insertResult.InsertedID)

}
